#a!/bin/bash
# Cesare de Filippo, MPI-EVA
# modified on 12-August-2013 
#$ -S /bin/bash
#$ -cwd
#$ -q all.q
# load personal profile
#$ -V
#$ -R y
#$ -M barbara_domingues@eva.mpg.de
#$ -m e
#$ -l h_vmem=1G,s_vmem=1G



for i in {1..1000};

do



#T2
./BALLET -T2 100 DivFile_neu PolySubFile_neu SpectFile_neu neu_SNPFile$i neu_RecFile$i /home/barbara_domingues/Downloads/simulated_spectra/ OutFile_T2_neu$i
#T2



done

