#!/bin/bash
# Cesare de Filippo, MPI-EVA
# modified on 12-August-2013
# also modified by Barbara Bitarello on 21.01.2014
#$ -S /bin/bash
#$ -cwd
#$ -q all.q
# load personal profile
#$ -V
#$ -R y
#$ -M barbara_domingues@eva.mpg.de
#$ -m e
#$ -l h_vmem=200M,s_vmem=200M



RSCRIPT=/mnt/sequencedb/PopGen/barbara/simulations/scripts/run_ncv_scan.r
INPUT=${2} # the imput file as allele counts such as (AC_13pops.tsv.gz)
POSITIONSFILE=${1} # the interval to use as CHROMOSOME, START and END positions
WINDOW=${3} # the window length in bp
SLIDE=${4}
CHIMPbed=${5}
CHIMPfd=${6}	
TMPDIR=${7}   # /mnt/sequencedb/PopGen/barbara/vcf_practice/DATA/chr21/tmpdir
SIM=${SGE_TASK_ID}


#OBS: run this script from within each DATA/chr21 (20, tc) directory.


nBINS=$(wc -l $POSITIONSFILE)

jesus=`echo ${nBINS}|awk '{print $1}'`; 

path_data=/mnt/sequencedb/PopGen/barbara/vcf_practice/DATA/chr

for i in `seq $jesus`  ; 
do 
POSITIONS=$(sed -n ${i}p $POSITIONSFILE)
CHROM=$(echo ${POSITIONS} | cut -f 1 -d ':' ) 
cd ${TMPDIR}
mkdir -p ${TMPDIR}${i}
cd ${TMPDIR}${i}
tabix -p vcf ${path_data}${CHROM}/${INPUT} ${POSITIONS} > tmp.ac
${RSCRIPT} tmp.ac ${WINDOW} ${SLIDE} ${CHIMPbed} ${CHIMPfd} chr${CHROM} > test${i}.log

cd ../../
echo DONE
done

##it's working!! Problem: some tmp.ac files will be empty because there are no snps on that window.



#example  qsub  (from within DATA/chr21/ , run:


#/mnt/sequencedb/PopGen/barbara/simulations/scripts/mnt/sequencedb/PopGen/barbara/simulations/scripts/ncv_scan.sge 'chr21.positions.txt' '/mnt/sequencedb/PopGen/barbara/vcf_practice/DATA/chr21/AC_13pops.Map50_100.TRF.SDs.tsv.gz' 3000 1500 '/mnt/sequencedb/PopGen/cesare/bs_genomescan/Map50_100.TRF.SDs.hg19_pantro2.21.bed' '/mnt/sequencedb/PopGen/cesare/bs_genomescan/fds.hg19_pantro2.21.tsv' tmpdir chr21 > log.test
